version: '3.8'

services:
  tv-telegram-webhook:
    build: .
    container_name: tv-telegram-webhook
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Isikan Token Bot dari BotFather
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      # Isikan Chat ID Grup atau Chat ID Anda
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
